### ISSUE TITLE
doctrine/mongodb-odm compatibility issue

### ISSUE THREAD

**Issue by Im-Anantha-Raman** [klapaudius/FOSOAuthServerBundle#25]
Doctrine Mongodb confihuration such as client.mongodb.xm, accestoken.mongodb.xml etc are not upto date with latest doctrine/mongodb-odm version

**Comment by androshchuk** [comment]
@klapaudius https://github.com/klapaudius/FOSOAuthServerBundle/pull/27 should fix it
