### ISSUE TITLE
UserBadge get clients identifier instead of users

### ISSUE THREAD

**Issue by shtumi** [klapaudius/FOSOAuthServerBundle#32]
Hello.

I'm trying to configure OAuth authentication for my API.

I see that `Oauth2Authenticator::authenticate` has the code:
`return new SelfValidatingPassport(new UserBadge($client->getUserIdentifier()), [$accessTokenBadge]);`

which creates `UserBadge`, but uses NOT the user's identifier, but the client's.
Therefore further Symfony authentication fails and I get "Invalid credentials." exception.
But if I replace `$client->getUserIdentifier()` with `$user->getUserIdentifier()`, then it becomes workable.

Is anything wrong with my config or is it an internal bug in this bundle?

**Comment by klapaudius** [comment]
Hi,

Please check #29
