### ISSUE TITLE
Backport return type on 3.0 branch

### ISSUE THREAD

**Issue by Thierrygen** [klapaudius/FOSOAuthServerBundle#33]
Hello, 
Is that possible to backport this return type on 3.0 and 4.0 branch ?

From this commit ? 
https://github.com/klapaudius/FOSOAuthServerBundle/commit/af7c4c5030db85946468c47d43420800acf39464#diff-fd37638a943de1034d576fcc1f367376d08780b9c5f00da35da15274ac967046R239

**Comment by klapaudius** [comment]
Hi, it is done new releases are coming.
